// Generated by CoffeeScript 1.3.3
var app, cons, express, haml, http, routes, server;

express = require('express');

routes = require('./routes');

haml = require('hamljs');

cons = require('consolidate');

http = require('http');

app = express();

app.configure(function() {
  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.engine('haml', cons.haml);
  app.set('view engine', 'haml');
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  return app.use(express["static"](__dirname + '/public'));
});

app.configure('development', function() {
  return app.use(express.errorHandler());
});

app.get('/', routes.index);

server = http.createServer(app);

server.listen(app.get('port'), function() {
  return console.log("Express server listening on port " + app.get('port'));
});
